### ISSUE TITLE
"DHCP Leases Online" showing 0 clients since Release 2023.3.5 HomeAssistant update

### ISSUE THREAD

**Issue by sluggy7584** [travisghansen/hass-pfsense#153]
I have tracked the DHCP Leases Online entity since I discovered this integration. At 10PM or so local time on March 16, an automatic update was applied to Home Assistant. Ever since then, this entity reports 0 clients, even though I can verify directly with pfsense that there are still 50-ish clients online. Other pfsense integration entities are reporting as expected. Any ideas? Thank you!

![chrome_KXXt8CtcrJ](https://user-images.githubusercontent.com/116283833/226436935-3a2f36cf-3aa1-4d52-b693-73b23d5a01f5.png)

**Comment by RJ1002** [comment]
I have the same issue for both online and offline. no errors in logs.
only this error im seeing but it seem to be unrelated:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/22334486/229225557-451a822c-6ea2-4646-8d2b-4e0230d1a53f.png">

![image](https://user-images.githubusercontent.com/22334486/229225756-af35d815-5690-4c28-bf84-159cfdfc4178.png)

**Comment by travisghansen** [comment]
Possibly fixed by this (https://github.com/travisghansen/hass-pfsense/commit/b1830454d5dd8de51d28b0db445e1a038fe8f4fe) can you try the latest version?

**Comment by sluggy7584** [comment]
> Possibly fixed by this ([b183045](https://github.com/travisghansen/hass-pfsense/commit/b1830454d5dd8de51d28b0db445e1a038fe8f4fe)) can you try the latest version?

That did it!  Thank you!
![image](https://user-images.githubusercontent.com/116283833/235501928-5f9b1053-b442-43c8-8184-708ac17ab612.png)

**Comment by Abarth91** [comment]
Hello everyone,

I still have the same problem. DHCP Leases Online shows 0. Offline and Total shows values.

![2023-12-15 09_06_17-vm_win10](https://github.com/travisghansen/hass-pfsense/assets/17790070/86fc94e1-1cd8-4ef9-8466-f112bae70f7b)

pfSense Version: 2.7.2-RELEASE (amd64)
